# Site settings
title: ARDIANSYAH
description: '<p>Mahasiswa Sistem Informasi TA 2014</p>
              <p>Fakultas : Sains dan Teknologi</p>
              <p>Universitas Islam Negeri Sultan Syarif Kasim Riau</p>'
url: 'http://Ardiansyah022.github.io'
baseurl: '/Ardiansyah022.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ardiansyah'
  email: ardiansyah541996@gmail.com
  instagram_username: ardhy022
  facebook_username: Dhy Ardiansyah
  github_username:  Ardiansyah022
  linkedin_username:  ardiansyah
  uin suska: http://uin-suska.ac.id/
  sif uin: http://sif.uin-suska.ac.id/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
